In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from Neuron.NeuronNetwork import Model
from fonction_activation.LeakyRelu import LeakyRelu

In [2]:
df = pd.read_csv('data/data.csv')
matrice = df.to_numpy()
matrice.shape

(568, 32)

In [3]:
random_matrice = np.random.rand(10, 3)
random_matrice

array([[0.25557391, 0.8258931 , 0.94814942],
       [0.37414469, 0.61429034, 0.58766329],
       [0.44290621, 0.98671034, 0.87879258],
       [0.86084436, 0.97666437, 0.55001523],
       [0.36487604, 0.12061722, 0.78732716],
       [0.75337134, 0.03108911, 0.33648419],
       [0.53321747, 0.36781743, 0.33553014],
       [0.52440858, 0.3494639 , 0.44297943],
       [0.49790254, 0.4126743 , 0.02240485],
       [0.60914701, 0.104869  , 0.99262565]])

In [4]:
unitaire = np.ones((random_matrice.shape[0], 1))
print(unitaire)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [5]:
new_matrice = np.c_[random_matrice, unitaire]
new_matrice.shape

(10, 4)

In [6]:
new_matrice

array([[0.25557391, 0.8258931 , 0.94814942, 1.        ],
       [0.37414469, 0.61429034, 0.58766329, 1.        ],
       [0.44290621, 0.98671034, 0.87879258, 1.        ],
       [0.86084436, 0.97666437, 0.55001523, 1.        ],
       [0.36487604, 0.12061722, 0.78732716, 1.        ],
       [0.75337134, 0.03108911, 0.33648419, 1.        ],
       [0.53321747, 0.36781743, 0.33553014, 1.        ],
       [0.52440858, 0.3494639 , 0.44297943, 1.        ],
       [0.49790254, 0.4126743 , 0.02240485, 1.        ],
       [0.60914701, 0.104869  , 0.99262565, 1.        ]])

In [8]:
model = Model()
model.add_layer(output_size=3, activation_function=LeakyRelu, input_size=4)
model.add_layer(output_size=3, activation_function=LeakyRelu)
model.add_layer(output_size=2, activation_function=LeakyRelu)

In [9]:
new_matrice

array([[0.25557391, 0.8258931 , 0.94814942, 1.        ],
       [0.37414469, 0.61429034, 0.58766329, 1.        ],
       [0.44290621, 0.98671034, 0.87879258, 1.        ],
       [0.86084436, 0.97666437, 0.55001523, 1.        ],
       [0.36487604, 0.12061722, 0.78732716, 1.        ],
       [0.75337134, 0.03108911, 0.33648419, 1.        ],
       [0.53321747, 0.36781743, 0.33553014, 1.        ],
       [0.52440858, 0.3494639 , 0.44297943, 1.        ],
       [0.49790254, 0.4126743 , 0.02240485, 1.        ],
       [0.60914701, 0.104869  , 0.99262565, 1.        ]])

In [9]:
vecteur = np.array([1, 2, 3, 4])
vecteur.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4]])

In [10]:
np.dot(new_matrice, vecteur.reshape(-1, 1))

array([[7.37809804],
       [7.79865926],
       [7.73858543],
       [6.02671168],
       [8.27089578],
       [7.08799402],
       [6.97668401],
       [7.75781059],
       [7.26012931],
       [5.39980403]])

In [10]:
model.forward(new_matrice)

array([[ 1.93173444e+00, -5.61975513e-03],
       [ 1.17737166e+00, -3.37464019e-03],
       [ 2.29399295e+00, -6.77894103e-03],
       [ 1.72630512e+00, -5.14959513e-03],
       [-1.90621780e-04,  3.41596417e-02],
       [-9.62362236e-05,  1.73163950e-02],
       [ 6.98529476e-02, -2.58235469e-05],
       [-1.37284508e-04,  2.44902338e-02],
       [ 6.79512076e-01, -1.95931809e-03],
       [ 2.10240879e-01, -3.87831639e-04]])

In [ ]:
dot_product = np.dot(random_matrice, random_vecteur)
dot_product

array([2.61077408, 3.45639661, 2.57217264, 3.40724596, 2.22215649,
       3.60934251, 3.67117727, 3.65586571, 3.96123408, 2.28167499])

In [ ]:
A = 10
addition = dot_product + A
addition

array([12.61077408, 13.45639661, 12.57217264, 13.40724596, 12.22215649,
       13.60934251, 13.67117727, 13.65586571, 13.96123408, 12.28167499])