In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from Neuron.NeuronNetwork import Model
from fonction_activation.LeakyRelu import LeakyRelu

In [2]:
df = pd.read_csv('data/data.csv')
matrice = df.to_numpy()
matrice.shape

(568, 32)

In [3]:
random_matrice = np.random.rand(10, 3)
random_matrice

array([[0.27947102, 0.42483868, 0.74964989],
       [0.58192581, 0.56741167, 0.69397004],
       [0.25515268, 0.38068358, 0.9073552 ],
       [0.33150474, 0.37960771, 0.31199718],
       [0.82285123, 0.9992389 , 0.48318892],
       [0.05469494, 0.56821805, 0.63228766],
       [0.21150249, 0.06017419, 0.88161104],
       [0.72212348, 0.24548358, 0.84823999],
       [0.18462945, 0.73701493, 0.53382333],
       [0.05286021, 0.20387655, 0.31306357]])

In [4]:
unitaire = np.ones((random_matrice.shape[0], 1))
print(unitaire)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [5]:
new_matrice = np.c_[random_matrice, unitaire]
new_matrice.shape

(10, 4)

In [6]:
new_matrice

array([[0.27947102, 0.42483868, 0.74964989, 1.        ],
       [0.58192581, 0.56741167, 0.69397004, 1.        ],
       [0.25515268, 0.38068358, 0.9073552 , 1.        ],
       [0.33150474, 0.37960771, 0.31199718, 1.        ],
       [0.82285123, 0.9992389 , 0.48318892, 1.        ],
       [0.05469494, 0.56821805, 0.63228766, 1.        ],
       [0.21150249, 0.06017419, 0.88161104, 1.        ],
       [0.72212348, 0.24548358, 0.84823999, 1.        ],
       [0.18462945, 0.73701493, 0.53382333, 1.        ],
       [0.05286021, 0.20387655, 0.31306357, 1.        ]])

In [7]:
model = Model()
model.add_layer(neuron_count=3, activation_function=LeakyRelu, input_size=4)
model.add_layer(neuron_count=3, activation_function=LeakyRelu)
model.add_layer(neuron_count=2, activation_function=LeakyRelu)

In [8]:
new_matrice

array([[0.27947102, 0.42483868, 0.74964989, 1.        ],
       [0.58192581, 0.56741167, 0.69397004, 1.        ],
       [0.25515268, 0.38068358, 0.9073552 , 1.        ],
       [0.33150474, 0.37960771, 0.31199718, 1.        ],
       [0.82285123, 0.9992389 , 0.48318892, 1.        ],
       [0.05469494, 0.56821805, 0.63228766, 1.        ],
       [0.21150249, 0.06017419, 0.88161104, 1.        ],
       [0.72212348, 0.24548358, 0.84823999, 1.        ],
       [0.18462945, 0.73701493, 0.53382333, 1.        ],
       [0.05286021, 0.20387655, 0.31306357, 1.        ]])

In [9]:
vecteur = np.array([1, 2, 3, 4])
vecteur.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4]])

In [10]:
np.dot(new_matrice, vecteur.reshape(-1, 1))

array([[7.37809804],
       [7.79865926],
       [7.73858543],
       [6.02671168],
       [8.27089578],
       [7.08799402],
       [6.97668401],
       [7.75781059],
       [7.26012931],
       [5.39980403]])

In [11]:
model.forward(new_matrice)

Layer 0: input shape (10, 4)
input[[0.27947102 0.42483868 0.74964989 1.        ]
 [0.58192581 0.56741167 0.69397004 1.        ]
 [0.25515268 0.38068358 0.9073552  1.        ]
 [0.33150474 0.37960771 0.31199718 1.        ]
 [0.82285123 0.9992389  0.48318892 1.        ]
 [0.05469494 0.56821805 0.63228766 1.        ]
 [0.21150249 0.06017419 0.88161104 1.        ]
 [0.72212348 0.24548358 0.84823999 1.        ]
 [0.18462945 0.73701493 0.53382333 1.        ]
 [0.05286021 0.20387655 0.31306357 1.        ]]
weights[[0.26570959]
 [0.25839017]
 [0.66957238]
 [0.96901759]]
[[1.65499472]
 [1.73491763]
 [1.74271898]
 [1.36409318]
 [1.76938052]
 [1.55373488]
 [1.63106666]
 [1.79228134]
 [1.56594618]
 [1.24536148]]
input[[0.27947102 0.42483868 0.74964989 1.        ]
 [0.58192581 0.56741167 0.69397004 1.        ]
 [0.25515268 0.38068358 0.9073552  1.        ]
 [0.33150474 0.37960771 0.31199718 1.        ]
 [0.82285123 0.9992389  0.48318892 1.        ]
 [0.05469494 0.56821805 0.63228766 1.        ]
 [0

ValueError: Input size must be 4, but got 10

In [ ]:
dot_product = np.dot(random_matrice, random_vecteur)
dot_product

array([2.61077408, 3.45639661, 2.57217264, 3.40724596, 2.22215649,
       3.60934251, 3.67117727, 3.65586571, 3.96123408, 2.28167499])

In [ ]:
A = 10
addition = dot_product + A
addition

array([12.61077408, 13.45639661, 12.57217264, 13.40724596, 12.22215649,
       13.60934251, 13.67117727, 13.65586571, 13.96123408, 12.28167499])